# Numpy Library

## Introduction :

><li>Numpy is a Python library.</li>
><li>Numpy is short for "Numerical Python".</li>
><li>Numpy is used for working with arrays.</li>
><li>An array is a data structure that contains a group of elements of the same data type,such as integer or string.Arrays are generally used to organize data for easy sorting and searching.</li>
><li>It also has functions for working in domain of linear algebra, fourier transform, and matrices.</li>
><li>NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.</li>
><li>Arrays can be created using numpy library or using array module.</li>

## Advantages :

><li>In Python we have lists that serve the purpose of arrays, but they are slow to process.</li>
><li>Numpy aims to provide an array object that is up to 50x faster than traditional Python lists.</li>
><li>The array object in Numpy is called "ndarray", it provides a lot of supporting functions that make working with ndarray very easy.</li>
><li>Arrays are very frequently used in data science, where speed and resources are very important</li>

## Creating an Array
> An array can be created using the **array()** function of **numpy library**.
> An array can also be created from an existing array using **copy()** and **view()** command.

In [2]:
import numpy #importing numpy library

In [3]:
#Creating an array of integers
array1=numpy.array([1,2,3,4,5],int)
print(array1,type(array1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
#Creating an array of characters
array2=numpy.array(['a','b','c','d','e'])
print(array2,type(array2))

['a' 'b' 'c' 'd' 'e'] <class 'numpy.ndarray'>


In [5]:
#Creating an array of strings
array3=numpy.array(['apple','orange','grapes','kiwi','mango'],str)
print(array3,type(array3))

['apple' 'orange' 'grapes' 'kiwi' 'mango'] <class 'numpy.ndarray'>


In [6]:
#Creating an array of floats
array4=numpy.array([0.125,0.5,1.15,1.5,2.15,2.5],dtype=float)
print(array4,type(array4))

[0.125 0.5   1.15  1.5   2.15  2.5  ] <class 'numpy.ndarray'>


##### Difference Between Copy and View!

>The main difference between a copy and a view of an array is that the **copy is a new array**, and the **view is just a view of the original array**.

>The **copy owns the data and any changes made to the copy will not affect original array**, and any changes made to the original array will not affect the copy.

>The **view does not own the data and any changes made to the view will affect the original array**, and any changes made to the original array will affect the view.

###### Using view() to create a new array from an existing array

In [7]:
array5=array4.view()
print(array5,type(array5))

[0.125 0.5   1.15  1.5   2.15  2.5  ] <class 'numpy.ndarray'>


###### Using copy() to create a new array from an existing array

In [8]:
array6=array3.copy()
print(array6,type(array6))

['apple' 'orange' 'grapes' 'kiwi' 'mango'] <class 'numpy.ndarray'>


##### Why is Numpy Faster than Lists?
>> Numpy arrays are **stored at one continuous place in memory** unlike lists, so processes can access and manipulate them very efficiently.This behavior is called **locality of reference** in computer science.This is the main reason why Numpy is faster than lists. Also it is optimized to work with latest CPU architectures. 

In [9]:
# Numpy is usually imported under the "np" alias.
# alias: In Python alias are an alternate name for referring to the same thing
import numpy as np

In [10]:
#Creating an array of integers
array1=np.array([1,2,3,4,5],int)
print(array1,type(array1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [11]:
##Checking Numpy Version
##The version string is stored under "__version__" attribute.

print(np.__version__)

1.20.3


## Dimensions in Arrays
>A dimension in arrays is one level of array depth (nested arrays : are arrays that have arrays as their elements).

>**ndim :** Numpy Arrays provides the ndim attribute that returns an integer that tells us how many dimensions does the array have.

#### 0-D Arrays
> 0-D arrays or Scalars, are the elements in an array. Each value in an array is a 0-D array.

In [12]:
# Creating a 0D array
arr1=np.array(100)
print("arr1=",arr1,"\nDimensions=",arr1.ndim,"\nType=",type(arr1))

arr1= 100 
Dimensions= 0 
Type= <class 'numpy.ndarray'>


#### 1-D Arrays
> An array that has **0-D arrays as its elements** is called **uni-dimensional or 1-D array**.
> A **1-D array** is an array of elements of similar data type starting from index **0** and ending at **n+1**

In [13]:
# Creating a 1D array
arr2=np.array((1,2,3,4,5),int)
print("arr2=",arr2,"\nDimensions=",arr2.ndim,"\nType=",type(arr2))

arr2= [1 2 3 4 5] 
Dimensions= 1 
Type= <class 'numpy.ndarray'>


#### 2-D Arrays
>An array that has **1-D arrays as its elements** is called a 2-D array.These are often used to represent **matrix or 2nd order tensors**.

>Numpy has a whole sub module dedicated towards matrix operations called **numpy.mat**

In [14]:
# Creating a 2D array containing two arrays 
arr3 = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]],int)
print("arr3=\n",arr3,"\nDimensions=",arr3.ndim,"\nType=",type(arr3))

arr3=
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 
Dimensions= 2 
Type= <class 'numpy.ndarray'>


#### 3-D Arrays
>An array that has **2-D arrays(matrices) as its elements** is called 3-D array.
>These are often used to represent a **3rd order tensor**.

In [15]:
#Creating a 3-D array with two 2-D arrays
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print("arr4=\n",arr4,"\nDimensions=",arr4.ndim,"\nType=",type(arr4))

arr4=
 [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]] 
Dimensions= 3 
Type= <class 'numpy.ndarray'>


#### Arrays having higher dimensions
> we can define the arrays with higher dimensions using **ndmin** argument.

In [16]:
# Creating a 5D array 
arr5 = np.array([1, 2, 3,4], ndmin=5)
print("arr5=\n",arr5,"\nDimensions=",arr5.ndim,"\nType=",type(arr5))

#In this array the innermost dimension (5th dim) has 4 elements, 
#the 4th dim has 1 element that is the vector, 
#the 3rd dim has 1 element that is the matrix with the vector, 
#the 2nd dim has 1 element that is 3D array and 
#1st dim has 1 element that is a 4D array.

arr5=
 [[[[[1 2 3 4]]]]] 
Dimensions= 5 
Type= <class 'numpy.ndarray'>


## Numpy Array Indexing

><li>Array indexing is the same as accessing an array element.</li>
><li>You can access an array element by referring to its index number.</li>
><li>The index in Numpy arrays start with 0,which means that the first element has index 0, and the second has index 1 etc.</li>

In [17]:
arr2

array([1, 2, 3, 4, 5])

In [18]:
# accessing the elements of arrays using indexes
arr2[0],arr2[1],arr2[-1],arr2[-5]

(1, 2, 5, 1)

In [19]:
#performing some arithmetic operations 
arr2[3]+arr2[-3],arr2[3]-arr2[-3],arr2[3]*arr2[-3]

(7, 1, 12)

##### Accessing 2-D Arrays
>To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

>Think of 2-D arrays like a table with rows and columns, where the **row represents the dimension** and the **index represents the column**.

In [20]:
arr3

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
arr3[1,2] #1->dimension.2->index position of the element you wanna access in the dimension

9

In [22]:
print(arr3[0,5])
print(arr3[1,4])

6
11


##### Access 3-D Arrays
> To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.

In [23]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)
print()
print("Dimensions=",arr.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

Dimensions= 3


In [24]:
arr[0,1,2] # 0->dim,1->dim,3rd value

6

In [25]:
print(arr[0,0,0])
print(arr[0,1,2])
print(arr[1,0,0])
print(arr[1,1,1])

1
6
7
11


* * *

In [26]:
arr5

array([[[[[1, 2, 3, 4]]]]])

In [27]:
print(arr5[0])
print(arr5[0,0])
print(arr5[0,0,0])
print(arr5[0,0,0,0])
print(arr5[0,0,0,0,0])

[[[[1 2 3 4]]]]
[[[1 2 3 4]]]
[[1 2 3 4]]
[1 2 3 4]
1


##### -ve indexing

In [33]:
arr2
print(arr2[-2])

4


In [35]:
arr3
print(arr3[-1,-3])

10


## Numpy arrays Slicing
><li>Slicing in python means taking elements from one given index to another given index.</li>
><li>We pass slice instead of index like this: [start:end].</li>
><li>We can also define the step, like this: [start:end:step].</li>
><li>If we don't pass start its considered 0.</li>
><li>If we don't pass end its considered length of array in that dimension.</li>
><li>If we don't pass step its considered 1.</li>

##### Slicing in 1-D arrays

In [61]:
arr=np.array([1,2,3,4,5,6,7,8],int)
arr,type(arr)

(array([1, 2, 3, 4, 5, 6, 7, 8]), numpy.ndarray)

In [62]:
print(arr[1:4])
print(arr[1:])
print(arr[:4])
print(arr[0:9:2])#using step=2
print(arr[1::])
print(arr[:6:])
print(arr[::2])

[2 3 4]
[2 3 4 5 6 7 8]
[1 2 3 4]
[1 3 5 7]
[2 3 4 5 6 7 8]
[1 2 3 4 5 6]
[1 3 5 7]


In [63]:
# -ve slicing
print(arr[-2:-5])# this gives empty list
print(arr[-5:-2])
print(arr[-2:-5:-2])

[]
[4 5 6]
[7 5]


##### Slicing in 2-D arrays

In [64]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [65]:
print(arr[0,0:3])
print(arr[1,1:3])
print(arr[1,0:5:2])
print(arr[0,0:5:2])
print(arr[0,0::])
print(arr[1,::5])
print(arr[0,:6:2])
print(arr[0,1:6:])
print(arr[0,:6:])

[1 2 3]
[7 8]
[ 6  8 10]
[1 3 5]
[1 2 3 4 5]
[6]
[1 3 5]
[2 3 4 5]
[1 2 3 4 5]


## Functions for 1-D Arrays

> In comparison to the array created by array module ,numpy arrays has access to many other **mathematical ,trignometric,statistical,logarithmic,and exponential functions**.

In [69]:
arr=numpy.array([10,18,15,12,13,19,16,6,16,16,16,12,11,3,10,16,9,1,18,5],int)
arr,type(arr)

(array([10, 18, 15, 12, 13, 19, 16,  6, 16, 16, 16, 12, 11,  3, 10, 16,  9,
         1, 18,  5]),
 numpy.ndarray)

##### Modifying the array elements

In [70]:
arr[0]=7
print(arr)

[ 7 18 15 12 13 19 16  6 16 16 16 12 11  3 10 16  9  1 18  5]


###### Determining the characteristics of the array

In [71]:
#The size of the array
arr.size

20

In [72]:
#datatype of the elements in the array
arr.dtype

dtype('int32')

###### Functions returning one single numeric output

In [73]:
#determining the mean
np.mean(arr)

11.95

In [74]:
#determining the median
np.median(arr)

12.5

In [76]:
#determining the min value in the array
np.min(arr)

1

In [77]:
#determining the max value in the array
np.max(arr)

19

In [78]:
#determining the sum of all values in the array
np.sum(arr)

239

In [79]:
#determining the product of all values in the array
np.prod(arr)

1342177280

In [80]:
#determining the covariance of all values in the array
np.cov(arr)

array(28.26052632)

##### What is covariance?
> Covariance is a measure of relationship between 2 random variables.The covariance indicates the **relationship between the 2 variables** and helps to know if the 2 variables vary together.
$$ Or $$
> Covariance provides the measure of strength of correlation between two variables or more set of variables.
>> <li>if Cov(Xi,Xj)=0 then variables are uncorrelated</li>
>> <li>if Cov(Xi,Xj)>0 then variables are  positively correlated</li>
>> <li>if Cov(Xi,Xj)<0 then variables are  negatively correlated</li>

##### Covariance Formula

##### covariance formula for population : 

$$Cov(X,Y)={\frac{\sum(X_{i}-\bar{X})(Y_{i}-\bar{Y})}n}$$

##### covariance formula for sample :

$$Cov(X,Y)={\frac{\sum(X_{i}-\bar{X})(Y_{i}-\bar{Y})}{n-1}}$$

$$Where,$$
$$ X_{i} \ is \ the \ values \ of \ the \ X-variable$$
$$ Y_{i} \ is \ the \ values \ of \ the \ Y-variable$$
$$ \bar{X} \ is \ the \ mean \ of \ the \ X-variable$$
$$ \bar{Y} \ is \ the \ mean \ of \ the \ Y-variable$$
$$ n \ is \ the \ number \ of \ data \ points$$

##### Relationship between correlation co-efficient and covariance is expressed as :
$${\frac{Cov(X,Y)}{\sigma_{X}\sigma_{Y}}}$$


$$Where,$$
$$ Cov(X,Y) \ is \ the \ covariance \ between \ X \ and \ Y$$
$$ \sigma_{X} and \sigma_{y} \ are \ the \ standard \ deviations \ of \ X \ and \ Y$$

##### Positive covariance:
> The two given variables tend to move in the **same direction**.

##### Negative covariance:
> The two given variables tend to move in the **inverse direction**.

In [81]:
#determining the variance of all values in the array
np.var(arr)

26.847499999999997

In [82]:
#determining the standard deviation of all values in the array
np.std(arr)

5.181457323958193

##### Mathematical functions returns an array output

In [91]:
# Sorting the element of the array
print("Before sorting = \n",arr)
print("After sorting=\n",np.sort(arr))

Before sorting = 
 [ 7 18 15 12 13 19 16  6 16 16 16 12 11  3 10 16  9  1 18  5]
After sorting=
 [ 1  3  5  6  7  9 10 11 12 12 13 15 16 16 16 16 16 18 18 19]


In [93]:
# finding the power of all the elements in a array
np.power(arr,2) #power(array,power_value)

array([ 49, 324, 225, 144, 169, 361, 256,  36, 256, 256, 256, 144, 121,
         9, 100, 256,  81,   1, 324,  25], dtype=int32)

In [94]:
# finding the square root of all the elements in a array
np.sqrt(arr) 

array([2.64575131, 4.24264069, 3.87298335, 3.46410162, 3.60555128,
       4.35889894, 4.        , 2.44948974, 4.        , 4.        ,
       4.        , 3.46410162, 3.31662479, 1.73205081, 3.16227766,
       4.        , 3.        , 1.        , 4.24264069, 2.23606798])

In [96]:
# returns the absolute value of all the elements in array
a1=np.array([1,-3,6,-3,8,-9,-10])
np.abs(a1)

array([ 1,  3,  6,  3,  8,  9, 10])

##### Trignometric functions also return an array output

In [97]:
np.sin(arr) #finding sine values of all the elements of array

array([ 0.6569866 , -0.75098725,  0.65028784, -0.53657292,  0.42016704,
        0.14987721, -0.28790332, -0.2794155 , -0.28790332, -0.28790332,
       -0.28790332, -0.53657292, -0.99999021,  0.14112001, -0.54402111,
       -0.28790332,  0.41211849,  0.84147098, -0.75098725, -0.95892427])

In [98]:
np.cos(arr) #finding cosine values of all the elements of array

array([ 0.75390225,  0.66031671, -0.75968791,  0.84385396,  0.90744678,
        0.98870462, -0.95765948,  0.96017029, -0.95765948, -0.95765948,
       -0.95765948,  0.84385396,  0.0044257 , -0.9899925 , -0.83907153,
       -0.95765948, -0.91113026,  0.54030231,  0.66031671,  0.28366219])

In [99]:
np.tan(arr) #finding tangent values of all the elements of array

array([ 8.71447983e-01, -1.13731371e+00, -8.55993401e-01, -6.35859929e-01,
        4.63021133e-01,  1.51589471e-01,  3.00632242e-01, -2.91006191e-01,
        3.00632242e-01,  3.00632242e-01,  3.00632242e-01, -6.35859929e-01,
       -2.25950846e+02, -1.42546543e-01,  6.48360827e-01,  3.00632242e-01,
       -4.52315659e-01,  1.55740772e+00, -1.13731371e+00, -3.38051501e+00])

##### Logarithmic functions also returns an array output

In [101]:
np.log(arr) #finding log values of all the elements of array

array([1.94591015, 2.89037176, 2.7080502 , 2.48490665, 2.56494936,
       2.94443898, 2.77258872, 1.79175947, 2.77258872, 2.77258872,
       2.77258872, 2.48490665, 2.39789527, 1.09861229, 2.30258509,
       2.77258872, 2.19722458, 0.        , 2.89037176, 1.60943791])

In [102]:
#finding log base 10 values of all the elements of array
np.log10(arr)

array([0.84509804, 1.25527251, 1.17609126, 1.07918125, 1.11394335,
       1.2787536 , 1.20411998, 0.77815125, 1.20411998, 1.20411998,
       1.20411998, 1.07918125, 1.04139269, 0.47712125, 1.        ,
       1.20411998, 0.95424251, 0.        , 1.25527251, 0.69897   ])

In [103]:
#finding exponential values of all the elements of array
np.exp(arr)

array([1.09663316e+03, 6.56599691e+07, 3.26901737e+06, 1.62754791e+05,
       4.42413392e+05, 1.78482301e+08, 8.88611052e+06, 4.03428793e+02,
       8.88611052e+06, 8.88611052e+06, 8.88611052e+06, 1.62754791e+05,
       5.98741417e+04, 2.00855369e+01, 2.20264658e+04, 8.88611052e+06,
       8.10308393e+03, 2.71828183e+00, 6.56599691e+07, 1.48413159e+02])

###### Mathematical operations on 1-D array

In [104]:
arr

array([ 7, 18, 15, 12, 13, 19, 16,  6, 16, 16, 16, 12, 11,  3, 10, 16,  9,
        1, 18,  5])

In [106]:
print("Addition operation=\n",arr+2)
print("Subtraction operation=\n",arr-1)
print("Multiplication operation=\n",arr*2)
print("Division operation=\n",arr/2)
print("Floor Division operation=\n",arr//2)
print("Modulus operation=\n",arr%2)

Addition operation=
 [ 9 20 17 14 15 21 18  8 18 18 18 14 13  5 12 18 11  3 20  7]
Subtraction operation=
 [ 6 17 14 11 12 18 15  5 15 15 15 11 10  2  9 15  8  0 17  4]
Multiplication operation=
 [14 36 30 24 26 38 32 12 32 32 32 24 22  6 20 32 18  2 36 10]
Division operation=
 [3.5 9.  7.5 6.  6.5 9.5 8.  3.  8.  8.  8.  6.  5.5 1.5 5.  8.  4.5 0.5
 9.  2.5]
Floor Division operation=
 [3 9 7 6 6 9 8 3 8 8 8 6 5 1 5 8 4 0 9 2]
Modulus operation=
 [1 0 1 0 1 1 0 0 0 0 0 0 1 1 0 0 1 1 0 1]


##### Program using multiple arrays  to perform mathematical operations

In [108]:
arr1=np.array([1,2,3,4,5])
arr2=np.array([6,7,8,9,10])
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [109]:
print("Addition operation=\n",arr1+arr2)
print("Subtraction operation=\n",arr1-arr2)
print("Multiplication operation=\n",arr1*arr2)
print("Division operation=\n",arr1/arr2)
print("Floor Division operation=\n",arr1//arr2)
print("Modulus operation=\n",arr1%arr2)

Addition operation=
 [ 7  9 11 13 15]
Subtraction operation=
 [-5 -5 -5 -5 -5]
Multiplication operation=
 [ 6 14 24 36 50]
Division operation=
 [0.16666667 0.28571429 0.375      0.44444444 0.5       ]
Floor Division operation=
 [0 0 0 0 0]
Modulus operation=
 [1 2 3 4 5]


##### Program using multiple arrays  to perform Relational operations

In [111]:
arr1==arr2

array([False, False, False, False, False])

In [112]:
arr1!=arr2

array([ True,  True,  True,  True,  True])

In [113]:
arr1>arr2

array([False, False, False, False, False])

In [114]:
arr1<arr2

array([ True,  True,  True,  True,  True])

In [115]:
arr1>=arr2

array([False, False, False, False, False])

In [116]:
arr1<=arr2

array([ True,  True,  True,  True,  True])

## Multidimensional Arrays
> The simplest form of multidimensional arrays are 2D arrays.A 2D array as **rows and columns**.It can also be considered as **list of 1D arrays**.A 2D array has size [m][n],where m is rows and n is columns

### Creating Multidimensional Arrays

> A Multidimensional array can be created using **array(),reshape(),matrix(),Zeros(),ones()** function.

>> A **2D array** is represented using [] for rows and columns and both the [] are inside the main [].

>> The **array()** function uses [] outside all elements to denote one row of the array.

>> The **matrix()** function uses semicolon (;) to separate a row from the other.

>> The **reshape()** function converts the 1D array into multidimensional array on the basis of specified arugment for rows and columns.

>> The **zeros() and ones()** function create multidimensional array of specified dimensions and fill them with zeros and ones, respectively.

In [123]:
# Creating 2D array using array()
array1=np.array([[10,20,30,40],[50,60,70,80]])
print("2D array using array function :\n",array1)
print("\nDimensions=",np.ndim(array1))

2D array using array function :
 [[10 20 30 40]
 [50 60 70 80]]

Dimensions= 2


In [125]:
# Creating 2D array using matrix()
array2=np.matrix('1 2;3 4;5 6')
print("2D array using matrix function :\n",array2)
print("\nDimensions=",np.ndim(array2))

2D array using matrix function :
 [[1 2]
 [3 4]
 [5 6]]

Dimensions= 2


In [136]:
# Creating 2D array using reshape()
array3=np.array([10,20,30,40,50,60])
array3=np.reshape(array3,(3,2)) # (2,3) indicates (rows and columns )
print("2D array using reshape function :\n",array3)
print("\nDimensions=",np.ndim(array3))

2D array using reshape function :
 [[10 20]
 [30 40]
 [50 60]]

Dimensions= 2


In [129]:
# Creating 2D array using zeros()
array4=np.zeros((4,2))
print("2D array using zeros function :\n",array4)
print("\nDimensions=",np.ndim(array4))

2D array using zeros function :
 [[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

Dimensions= 2


In [130]:
# Creating 2D array using ones()
array5=np.ones((3,3))
print("2D array using zeros function :\n",array5)
print("\nDimensions=",np.ndim(array5))

2D array using zeros function :
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Dimensions= 2


### Accessing elements in Multi-Dimensional arrays using Indexing and slicing

In [143]:
print(array1)


[[10 20 30 40]
 [50 60 70 80]]


In [142]:
#Indexing
print(array1[0][0])
print(array1[0][2])
print(array1[0][3])
print(array1[1][1])
print(array1[1][2])
print(array1[1][3])

10
30
40
60
70
80


In [144]:
arr=np.reshape(range(10,50,2),(4,5))
arr

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [152]:
# Slicing
print(arr[:,:]) #displaying all elements
print()
print(arr[0:2,]) #displayint 1st 2 rows 
print()
print(arr[2,]) #displaying only 2 row
print()
print(arr[0:2,0:2]) #displaying elements of 1st 2rows and 2 columns
print()
print(arr[1,1:4]) #displaying only 1st row 3rd,4th, and 5th column value

[[10 12 14 16 18]
 [20 22 24 26 28]
 [30 32 34 36 38]
 [40 42 44 46 48]]

[[10 12 14 16 18]
 [20 22 24 26 28]]

[30 32 34 36 38]

[[10 12]
 [20 22]]

[22 24 26]


### Functions on multidimensional arrays

In [154]:
arr=np.matrix('1 2 3;4 5 6;7 8 9;10 11 12')
arr

matrix([[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]])

In [155]:
# transpose()-> gives the transpose of a matrix
arr.transpose()

matrix([[ 1,  4,  7, 10],
        [ 2,  5,  8, 11],
        [ 3,  6,  9, 12]])

In [156]:
# ndim functions gives the dimensions of the array
arr.ndim

2

In [157]:
# The shape determines the shape of the array
arr.shape

(4, 3)

In [161]:
# flatten() flattens matrix and converts into 1D 
a=arr.flatten()
print("a=",a)
print(a.ndim)

a= [[ 1  2  3  4  5  6  7  8  9 10 11 12]]
2


In [179]:
arr=np.matrix('3 1 2;7 9 8;6 5 4;11 12 10')
arr

matrix([[ 3,  1,  2],
        [ 7,  9,  8],
        [ 6,  5,  4],
        [11, 12, 10]])

In [180]:
# sort() with axis=1(default) sorts the matrix on row basis
np.sort(arr,axis=1)

matrix([[ 1,  2,  3],
        [ 7,  8,  9],
        [ 4,  5,  6],
        [10, 11, 12]])

In [181]:
# sort() with axis=0(default) sorts the matrix on column basis
np.sort(arr,axis=0)

matrix([[ 3,  1,  2],
        [ 6,  5,  4],
        [ 7,  9,  8],
        [11, 12, 10]])

In [187]:
# the diagonal() function helps to determine the diagonal elements
np.diagonal(arr)

array([3, 9, 4])

##### Mathematical operations on Multidimensional arrays

In [205]:
arr1=np.matrix('1 2 3;13 14 15;7 8 9')
arr2=np.matrix('10 11 12;13 14 15;4 5 6')
print(arr1)
print()
print(arr2)

[[ 1  2  3]
 [13 14 15]
 [ 7  8  9]]

[[10 11 12]
 [13 14 15]
 [ 4  5  6]]


In [206]:
arr1+arr2

matrix([[11, 13, 15],
        [26, 28, 30],
        [11, 13, 15]])

In [207]:
arr1-arr2

matrix([[-9, -9, -9],
        [ 0,  0,  0],
        [ 3,  3,  3]])

In [208]:
arr1*arr2

matrix([[ 48,  54,  60],
        [372, 414, 456],
        [210, 234, 258]])

In [209]:
print(arr1/arr2)#only element wise matrix  division is possible 
print("\n",arr1//arr2 )

[[0.1        0.18181818 0.25      ]
 [1.         1.         1.        ]
 [1.75       1.6        1.5       ]]

 [[0 0 0]
 [1 1 1]
 [1 1 1]]


In [210]:
print(arr1%arr2)

[[1 2 3]
 [0 0 0]
 [3 3 3]]


##### Relational operations on multi-dimensional arrays


In [211]:
arr1==arr2

matrix([[False, False, False],
        [ True,  True,  True],
        [False, False, False]])

In [212]:
arr1!=arr2

matrix([[ True,  True,  True],
        [False, False, False],
        [ True,  True,  True]])

In [214]:
arr1>arr2

matrix([[False, False, False],
        [False, False, False],
        [ True,  True,  True]])

In [215]:
arr1<arr2

matrix([[ True,  True,  True],
        [False, False, False],
        [False, False, False]])

In [216]:
arr1>=arr2

matrix([[False, False, False],
        [ True,  True,  True],
        [ True,  True,  True]])

In [217]:
arr1<=arr2

matrix([[ True,  True,  True],
        [ True,  True,  True],
        [False, False, False]])

* * *

##### linspace()
> The linspace() function is a tool in numpy for **creating numeric sequence**.It is used to create an **evenly spread sequence in a specified range**.
<code>Syntax:
    numpy.linspace(start,stop,num=50,endpoint=True,retstep=False,dtype=None)</code>
   

In [238]:
a=np.linspace(0,10,10)
a

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

* * *

### Array operations

In [239]:
matrix1=np.matrix('1 2 3;4 5 6;7 8 9')
matrix1

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [240]:
np.linalg.inv(matrix1) # to find the inverse of the matrix

matrix([[ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15],
        [-6.30503948e+15,  1.26100790e+16, -6.30503948e+15],
        [ 3.15251974e+15, -6.30503948e+15,  3.15251974e+15]])

### Good to know!

>**Inverse of a matrix :**
>>Inverse of Matrix for a matrix A is denoted by A<sup>-1</sup>. The inverse of a 2 × 2 matrix can be calculated using a simple formula. Further, to find the inverse of a 3 × 3 matrix, we need to know about the determinant and adjoint of the matrix. 

###### The inverse matrix formula for a matrix A is given as,
$$A^{-1}= {\frac{adj(A)}{|A|}} |A|≠ 0 \ where \ A \ is \ a \ square \ matrix $$

>**NOTE:** For inverse of a matrix to exist:
><li>The given matrix should be a square matrix.</li>
><li>The determinant of the matrix should not be equal to zero</li>

>**Singular Matrix :** A matrix having a determinant value of zero is referred to as a singular matrix. For a singular matrix A, |A| = 0. The inverse of a singular matrix does not exist.

>**Non-Singular Matrix :** A matrix whose determinant value is not equal to zero is referred to as a non-singular matrix. For a non-singular matrix |A| ≠ 0. A non-singular matrix is called an invertible matrix since its inverse can be calculated.

>**Minor :** The minor is defined for every element of a matrix. The minor of a particular element is the determinant obtained after eliminating the row and column containing this element.

> **Cofactor :** The cofactor of an element is calculated by multiplying the minor with -1 to the exponent of the sum of the row and column elements in order representation of that element.

$$ cofactor=a_{ij}=(-1)^{(i + j)} * minor \ of \ a_{ij}$$

> **Determinant:** The determinant of a matrix is the single unique value representation of a matrix. The determinant of the matrix can be calculated with reference to any row or column of the given matrix. The determinant of the matrix is equal to the summation of the product of the elements and its cofactors, of a particular row or column of the matrix.


In [241]:
np.linalg.det(matrix1)   # to find the determinant of the matrix 

-9.51619735392994e-16

In [243]:
np.flipud(matrix1) # flips the matrix upside down

matrix([[7, 8, 9],
        [4, 5, 6],
        [1, 2, 3]])

In [244]:
np.flipud(matrix1).diagonal()  # fetching the diagonal elements after flipping the matrix

matrix([[7, 5, 3]])

In [246]:
np.fliplr(matrix1) # flips the matrix left-to-right 

matrix([[3, 2, 1],
        [6, 5, 4],
        [9, 8, 7]])

In [247]:
matrix1.trace()  # gives the sum of the main diagonal elements!!

matrix([[15]])

In [248]:
matrix1.T   # matrix transpose (convert the rows into columns)

matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

In [249]:
np.linalg.matrix_rank(matrix1)  # matrix has 3 columns, BUT the rank is 2
# (there are only 2 independent cols)
# clearly tells us that one of the columns represented as some functions of one of the other column.

2

In [250]:
eig_values, eig_vectors = np.linalg.eig(matrix1)

In [251]:
eig_values

array([ 1.61168440e+01, -1.11684397e+00, -3.38433605e-16])

In [252]:
eig_vectors 

matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]])

In [253]:
v = [1,3,6]
np.diag(v)   # creates a DIAGONAL Matrix (only the main diag elelments are NON-ZERO)

array([[1, 0, 0],
       [0, 3, 0],
       [0, 0, 6]])

In [254]:
np.eye(4)  # special case of a diagonal matrix (non-zero elements are one!!)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [255]:
np.logspace(0, 3, 10, base=2) 

array([1.        , 1.25992105, 1.58740105, 2.        , 2.5198421 ,
       3.1748021 , 4.        , 5.0396842 , 6.34960421, 8.        ])